language: node_js
node_js:
  - "6"

env:
  - CXX=g++-4.8

addons:
  code_climate:
    repo_token: 1ebfda221373077622c94fc4d90e02fe4bf9ddd17904950c0ead8cdbb74e14ef
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - wget http://www.us.apache.org/dist/kafka/0.10.0.0/kafka_2.11-0.10.0.0.tgz -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
  - sleep 10
  - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
  - sleep 10
  - kafka/bin/kafka-topics.sh --zookeeper 127.0.0.1:2181 --create --topic bunyan-nokafka --partitions 4 --replication-factor 1

after_script:
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=1ebfda221373077622c94fc4d90e02fe4bf9ddd17904950c0ead8cdbb74e14ef codeclimate-test-reporter < coverage/lcov.info